application: countrysportsbet
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

inbound_services:
- warmup
- mail

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: /static/admin/
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /static/
  static_dir: static
  expiration: '0'

- url: /.*
  script: djangoappengine.main.application
